spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_sso?useTimezone=true&serverTimezone=GMT%2b8&characterEncoding=utf8
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  thymeleaf:
    cache:false
server:
  port: 15080